### ISSUE TITLE
UnleashFetcher: Couldn't parse data

### ISSUE THREAD

**Issue by schnaps1981** [Unleash/unleash-android-proxy-sdk#16]
2022-03-22 16:09:00.921 13089-13125/com.example.unleash W/i*.g*.p*.UnleashFetcher: Couldn't parse data
    com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "impressionData" (class io.getunleash.data.Toggle), not marked as ignorable (3 known properties: "enabled", "name", "variant"])
        at [Source: (String)"{"toggles":[{"name":"toggle_1","enabled":true,"variant":{"name":"disabled","enabled":false},"impressionData":false},{"name":"toggle_2","enabled":true,"variant":{"name":"disabled","enabled":false},"impressionData":false},{"name":"toggle_3","enabled":true,"variant":{"name":"disabled","enabled":false},"impressionData":false},{"name":"toggle_"[truncated 413 chars]; line: 1, column: 150] (through reference chain: io.getunleash.data.ProxyResponse["toggles"]->java.util.ArrayList[0]->io.getunleash.data.Toggle["impressionData"])
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:987)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1974)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1701)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1679)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:294)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:473)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3531)
        at io.getunleash.polling.UnleashFetcher$getResponseAsync$1.onResponse(UnleashFetcher.kt:129)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by chriswk** [comment]
Hi. Sorry for the delayed catch of this ticket. We'll publish a fix that ignores unknown fields. It was an oversight to not set that flag initially

**Comment by chriswk** [comment]
We've released 0.4.0 which now ignores unknown fields. It's currently propagating to maven central mirrors
