### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by howseen** [Unleash/unleash-android-proxy-sdk#59]
### Describe the bug

Seems you doesn't use a proper data structure for handling concurrent access to the list

### Logs, error output, etc.

```bash
java.util.ConcurrentModificationException: null
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
    at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:790)
    at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFieldsUsing(SourceFile:902)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(SourceFile:762)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(SourceFile:720)
    at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(SourceFile:35)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(SourceFile:728)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(SourceFile:774)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(SourceFile:178)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(SourceFile:728)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(SourceFile:774)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(SourceFile:178)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(SourceFile:480)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(SourceFile:319)
    at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(SourceFile:4572)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(SourceFile:3825)
    at io.getunleash.metrics.HttpMetricsReporter.reportMetrics(SourceFile:94)
    at io.getunleash.UnleashClient$special$$inlined$timer$1.run
    at java.util.TimerThread.mainLoop(Timer.java:562)
    at java.util.TimerThread.run(Timer.java:512)
    
    
com.fasterxml.jackson.databind.JsonMappingException: (was java.util.ConcurrentModificationException) (through reference chain: io.getunleash.metrics.Report["bucket"]->io.getunleash.metrics.Bucket["toggles"])
    at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(SourceFile:316)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(SourceFile:782)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(SourceFile:178)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(SourceFile:728)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(SourceFile:774)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(SourceFile:178)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(SourceFile:480)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(SourceFile:319)
    at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(SourceFile:4572)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(SourceFile:3825)
    at io.getunleash.metrics.HttpMetricsReporter.reportMetrics(SourceFile:94)
    at io.getunleash.UnleashClient$special$$inlined$timer$1.run
    at java.util.TimerThread.mainLoop(Timer.java:562)
    at java.util.TimerThread.run(Timer.java:512)
```

### Unleash version

0.5.5

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by chriswk** [comment]
Thank you @howseen for this bug report. I'll have a look today to see if I can't replace the list here with something more apt for concurrent modifications.
