### ISSUE TITLE
crash on android 5 and 6

### ISSUE THREAD

**Issue by ehsan323** [Unleash/unleash-android-proxy-sdk#79]
### Describe the bug

After releasing new version of app by unleash, I saw many crashes on androids of 5 and 6

### Logs, error output, etc.

```bash
java.lang.NoClassDefFoundError: v7.b
	at io.getunleash.metrics.HttpMetricsReporter.log(SourceFile:3)
	at io.getunleash.UnleashClient.isEnabled(SourceFile:2)
	at io.getunleash.UnleashClientSpec$DefaultImpls.isEnabled$default(SourceFile)
	at com.emofid.rnmofid.presentation.ui.splash.SplashScreenActivity$onCreate$1$1.invokeSuspend(SourceFile:4)
	at l9.a.resumeWith(SourceFile:3)
	at kotlinx.coroutines.DispatchedTaskKt.resume(SourceFile:10)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(SourceFile:8)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:2)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:5)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(SourceFile)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(SourceFile:2)
	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(SourceFile)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6934)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException
```

### Unleash version

1.0.0

### Subscription type

None

### Hosting type

Self-hosted

**Comment by chriswk** [comment]
The plan is to release a new Android SDK sometime in July. Taking the lessons learned from this version and having an SDK that knows it's an Android library. It should simplify testing for us as well. If you're interested in following our progress, the new repo is at https://github.com/Unleash/UnleashAndroidSdk

**Comment by gastonfournier** [comment]
There's a new SDK released, please let us know if that solves this issue or else please open a new one with the details in the new repository: https://github.com/Unleash/unleash-android

Here's a migration guide to help with the migration https://github.com/Unleash/unleash-android/blob/main/docs/MigrationGuide.md
